In [5]:
import sys

!{sys.executable} -m pip install pandas

zsh:1: no such file or directory: /Users/harshpandey/task

In [6]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 3.0.6

## 1. Load Dataset

In [ ]:
import sys
print(sys.executable)

/Users/harshpandey/task 8/.venv/bin/python

In [ ]:
import sys
!{sys.executable} -m pip install pandas

In [11]:
import sys

print(sys.executable)

/Users/harshpandey/task 8/.venv/bin/python

In [12]:
%pip install pandas

Requirement already satisfied: pandas in /Users/harshpandey/task 8/.venv/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in /Users/harshpandey/task 8/.venv/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/harshpandey/task 8/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/harshpandey/task 8/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [16]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 3.0.6

# Sales Analytics & Prediction Dashboard

## Objective

Load and initially inspect a sales dataset for future analytics and prediction.

## 1. Import Libraries

In [17]:
import pandas as pd

## 2. Load Dataset

In [19]:
df = pd.read_csv("sales.csv")

In [20]:
df

         Date     Product     Category  Quantity  Price  Revenue
0  2026-09-01      Laptop  Electronics         2  50000   100000
1  2026-09-02       Mouse  Electronics         5   1000     5000
2  2026-09-03    Keyboard  Electronics         3   2500     7500
3  2026-09-04     Monitor  Electronics         2  15000    30000
4  2026-09-05  Headphones        Audio         4   3000    12000
5  2026-09-06     Speaker        Audio         3   4500    13500
6  2026-09-07      Laptop  Electronics         1  50000    50000
7  2026-09-08       Mouse  Electronics         8   1000     8000
8  2026-09-09    Keyboard  Electronics         4   2500    10000
9  2026-09-10     Monitor  Electronics         1  15000    15000

## 3. Inspect Dataset

In [21]:
df.head()

         Date     Product     Category  Quantity  Price  Revenue
0  2026-09-01      Laptop  Electronics         2  50000   100000
1  2026-09-02       Mouse  Electronics         5   1000     5000
2  2026-09-03    Keyboard  Electronics         3   2500     7500
3  2026-09-04     Monitor  Electronics         2  15000    30000
4  2026-09-05  Headphones        Audio         4   3000    12000

In [22]:
df.tail()

         Date   Product     Category  Quantity  Price  Revenue
5  2026-09-06   Speaker        Audio         3   4500    13500
6  2026-09-07    Laptop  Electronics         1  50000    50000
7  2026-09-08     Mouse  Electronics         8   1000     8000
8  2026-09-09  Keyboard  Electronics         4   2500    10000
9  2026-09-10   Monitor  Electronics         1  15000    15000

In [23]:
df.shape

(10, 6)

In [24]:
df.columns

Index(['Date', 'Product', 'Category', 'Quantity', 'Price', 'Revenue'], dtype='str')

In [25]:
df.dtypes

Date          str
Product       str
Category      str
Quantity    int64
Price       int64
Revenue     int64
dtype: object

## 4. Dataset Structure

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      10 non-null     str
 1   Product   10 non-null     str
 2   Category  10 non-null     str
 3   Quantity  10 non-null     int64
 4   Price     10 non-null     int64
 5   Revenue   10 non-null     int64
dtypes: int64(3), str(3)
memory usage: 612.0 bytes

## 5. Basic Statistics

In [27]:
df.describe()

        Quantity         Price        Revenue
count  10.000000     10.000000      10.000000
mean    3.300000  14450.000000   25100.000000
std     2.110819  19452.863257   29620.563428
min     1.000000   1000.000000    5000.000000
25%     2.000000   2500.000000    8500.000000
50%     3.000000   3750.000000   12750.000000
75%     4.000000  15000.000000   26250.000000
max     8.000000  50000.000000  100000.000000

## 6. Data Quality Check

In [28]:
df.isnull().sum()

Date        0
Product     0
Category    0
Quantity    0
Price       0
Revenue     0
dtype: int64

## 7. Initial Sales Analysis

In [29]:
df["Revenue"].sum()

np.int64(251000)

In [30]:
df["Quantity"].sum()

np.int64(33)

In [31]:
df.groupby("Product")["Revenue"].sum()

Product
Headphones     12000
Keyboard       17500
Laptop        150000
Monitor        45000
Mouse          13000
Speaker        13500
Name: Revenue, dtype: int64

In [32]:
df.groupby("Category")["Revenue"].sum()

Category
Audio           25500
Electronics    225500
Name: Revenue, dtype: int64

In [33]:
df.groupby("Product")["Revenue"].sum().sort_values(ascending=False)

Product
Laptop        150000
Monitor        45000
Keyboard       17500
Speaker        13500
Mouse          13000
Headphones     12000
Name: Revenue, dtype: int64

In [34]:
print("===== DATASET OVERVIEW =====")

print("Dataset Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nFirst 5 Rows:")
display(df.head())

print("\nBasic Statistics:")
display(df.describe())

===== DATASET OVERVIEW =====
Dataset Shape: (10, 6)

Columns:
['Date', 'Product', 'Category', 'Quantity', 'Price', 'Revenue']

Data Types:
Date          str
Product       str
Category      str
Quantity    int64
Price       int64
Revenue     int64
dtype: object

Missing Values:
Date        0
Product     0
Category    0
Quantity    0
Price       0
Revenue     0
dtype: int64

First 5 Rows:

         Date     Product     Category  Quantity  Price  Revenue
0  2026-09-01      Laptop  Electronics         2  50000   100000
1  2026-09-02       Mouse  Electronics         5   1000     5000
2  2026-09-03    Keyboard  Electronics         3   2500     7500
3  2026-09-04     Monitor  Electronics         2  15000    30000
4  2026-09-05  Headphones        Audio         4   3000    12000

Basic Statistics:

        Quantity         Price        Revenue
count  10.000000     10.000000      10.000000
mean    3.300000  14450.000000   25100.000000
std     2.110819  19452.863257   29620.563428
min     1.000000   1000.000000    5000.000000
25%     2.000000   2500.000000    8500.000000
50%     3.000000   3750.000000   12750.000000
75%     4.000000  15000.000000   26250.000000
max     8.000000  50000.000000  100000.000000

In [14]:
print("Data Science Task 8")

Data Science Task 8